

close all
clear

load data_ma_macropru.mat

s0 = simulate( ...
    m, dbin, startSim:endSim ...
    , "prependInput", true ...
    , "method", "stacked" ...
    , "Solver"     , {"Iris-Newton", "SkipJacobUpdate", 0,'FunctionTolerance', 1e-8,'StepTolerance',Inf,...
                             "FunctionNorm", Inf, "Display=","Iter"} ...
              );

