
close all
clear


r = rephrase.Report("");

x = rand(5);
x(2,2) = NaN;

r + rephrase.Matrix( ...
    "Correlation matrix", x ...
);

r + rephrase.Matrix( ...
    "Correlation matrix / NaN string", x ...
    , "NaN", "???" ...
);

r + rephrase.Matrix( ...
    "Correlation matrix / 4 decimals", x ...
    , "numDecimals", 4 ...
);

r + rephrase.Matrix( ...
    "Correlation matrix", x ...
    , "rowNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
);

r + rephrase.Matrix( ...
    "Correlation matrix", x ...
    , "rowNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
    , "columnNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
);

y = {'a', 1; 4.40292, 'cccc'};
r + rephrase.Matrix( ...
    "Matrix from cell array", y ...
);


%build(r, "matrixTest", [], "source", "web", "template", "./test-template.html");
build(r, "matrixTest", [], "source", "web");

