
close all
clear


r = rephrase.Report("");

x = rand(5);
x(2,2) = NaN;

r + rephrase.Matrix( ...
    "Correlation matrix", x ...
);

r + rephrase.Matrix( ...
    "Correlation matrix / NaN string", x ...
    , "NaN", "???" ...
);

r + rephrase.Matrix( ...
    "Correlation matrix / 4 decimals", x ...
    , "numDecimals", 4 ...
);

r + rephrase.Matrix( ...
    "Correlation matrix", x ...
    , "rowNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
);

r + rephrase.Matrix( ...
    "Correlation matrix", x ...
    , "rowNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
    , "columnNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
);

y = {'a', 1; 4.40292, 'cccc'};
r + rephrase.Matrix( ...
    "Matrix from cell array", y ...
);

x = rand(1, 5);

r + rephrase.Matrix( ...
    "Row vector", x ...
    , "rowNames", "first" ...
    , "columnNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
);

r + rephrase.Matrix( ...
    "Column vector", reshape(x, [], 1) ...
    , "columnNames", "first" ...
    , "rowNames", ["aaa", "b", "cc", "ddddd", "ee"] ...
);

build(r, "matrixTest", [], "source", "web");

