
startDateQ = qq(2020,1);
endDateQ = qq(2020,4);

report = rephrase.Report("Y-axis test");

grid2 = rephrase.Grid("Rounding", [], 2, "pass", {"showTitle", true, "dateFormat", "YYYY:Q"});

    c = 15901;
    x = c + Series(startDateQ:endDateQ, @rand) * 1e-8;

    chart1 = rephrase.SeriesChart.fromSeries( ...
        {"Small numbers not rounded", startDateQ:endDateQ} ...
        , {"XXX", x} ...
    );

    chart2 = rephrase.SeriesChart.fromSeries( ...
        {"Small numbers rounded to 7", startDateQ:endDateQ} ...
        , {"XXX", x, "round", 7} ...
    );

    layout = struct();
    layout.yaxis.tickmode = "array";
    layout.yaxis.tickvals = c-100:c+100;
    chart3 = rephrase.SeriesChart.fromSeries( ...
        {"Small numbers, tickvals", startDateQ:endDateQ, "Layout", layout} ...
        , {"XXX", x} ...
    );

    layout = struct();
    layout.yaxis.tickmode = "linear";
    layout.yaxis.tick0 = c-100;
    layout.yaxis.dtick = 1;
    chart4 = rephrase.SeriesChart.fromSeries( ...
        {"Small numbers, tick0+dtick", startDateQ:endDateQ, "Layout", layout} ...
        , {"XXX", x} ...
    );

    layout = struct();
    layout.yaxis.autorange = false;
    layout.yaxis.tick0 = c-100;
    layout.yaxis.dtick = 1;
    layout.yaxis.range = [c-2.5, c+2.1];
    %layout.yaxis.tickmode = "array";
    %layout.yaxis.tickvals = c-100:c+100;
    chart5 = rephrase.SeriesChart.fromSeries( ...
        {"Small numbers, range", startDateQ:endDateQ, "Layout", layout} ...
        , {"XXX", x} ...
    );


report + (grid2 + chart1 + chart2 + chart3 + chart4 + chart5);

report + rephrase.Pagebreak( );

fileNames = build( ...
    report, "yaxisTest", [] ...
    , "saveJSON", true ...
    , "source", ["local", "bundle", "web"] ...
);

