
% Set Up Once

testCase = matlab.unittest.FunctionTestCase.fromFunction(@(x)x);


%% Test Mixed

output = textual.interp( ...
    '$(a)+$(b)+$(cc)+$(e)+$(f)+$(g)' ...
    , struct('a',1) ...
    , struct('bb','20') ...
    , {'b:', 'B'} ...
    , {'e:', 1000} ...
    , 'f:   -5 ' ...
    , "g:   -x " ...
    , ["cc:","300"] ...
);

assertEqual(testCase, output, '1+B+300+1000+-5+-x');

