
testCase = matlab.unittest.FunctionTestCase.fromFunction(@(x)x);

%% Test Foreign Language Month Names

mo = {'Leden', 'Unor', 'Brezen', 'Duben', 'Kveten', 'Cerven', 'Cervenec', 'Srpen', 'Zari', 'Rijen', 'Listopad', 'Prosinec'};

c = databank.fromCSV( ...
    'monthNamesInCSVTest.csv', ...
    'SkipRows', 1, ...
    'NameRow', 'Date of Observation', ...
    'CommentRow', 3, ...
    'DateFormat', 'Mmm-YY', ...
    'EnforceFrequency', Frequency.QUARTERLY, ...
    'Months', mo ...
);

assertEqual(testCase, isfield(c, 'GDP'), true);
assertEqual(testCase, isfield(c, 'GDP'), true);
assertEqual(testCase, numel(c.GDP.Data), 5);
assertEqual(testCase, numel(c.CPI.Data), 5);

