
testCase = matlab.unittest.FunctionTestCase.fromFunction(@(x)x);

% Set up Once

startQ = qq(1990,1);
endQ = qq(2050,4);
startY = convert(startQ, Frequency.YEARLY) + 1;
endY = convert(endQ, Frequency.YEARLY);
quarterly = cumprod(1 + Series(startQ:endQ, @randn)/100);
indicator = quarterly + Series(startQ:endQ, @randn)/100;
yearly = convert(quarterly, Frequency.YEARLY, "Method=", "sum");


%% Test Initial Condition

interp = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Hard.Level=", clip(quarterly, -Inf, startQ+3) ...
);

assertEqual(testCase, interp(startQ+2:startQ+3), quarterly(startQ+2:startQ+3), "AbsTol", 1e-12);


%% Test Initial Condition and Hard Level


for k = 4 : 40
    interp = genip( ...
        yearly, Frequency.QUARTERLY, 2, "sum" ...
        , "Range=", startY:endY ...
        , "Hard.Level=", clip(quarterly, -Inf, startQ+k) ...
    );

    assertEqual(testCase, interp(startQ+2:startQ+k), quarterly(startQ+2:startQ+k), "AbsTol", 1e-12);
end


%% Test Hard Level but No Initial Condition

interp1 = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Hard.Level=", clip(quarterly, startQ+4, startQ+12) ...
);

interp2 = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Initial=", NaN ...
    , "Hard.Level=", clip(quarterly, -Inf, startQ+12) ...
);

assertEqual(testCase, interp1(startQ+4:end), interp2(startQ+4:end), "AbsTol", 1e-12);
assertEqual(testCase, interp1(startQ+(4:12)), quarterly(startQ+(4:12)), "AbsTol", 1e-12);

%% Test Indicator

interp1 = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Hard.Level=", clip(quarterly, -Inf, startQ+40) ...
);

interp2 = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Hard.Level=", clip(quarterly, -Inf, startQ+40) ...
    , "Indicator.Level=", indicator ...
    , "Indicator.Model=", "Ratio" ...
);

[~, r1] = acf(pct([interp1, indicator]));
[~, r2] = acf(pct([interp2, indicator]));

assertGreaterThan(testCase, r2(1), r1(2));


%% Test Indicator and Hard Level

indicator1 = indicator;
indicator2 = clip(indicator, startQ+38, Inf);
indicator2 = fillMissing(indicator2, startQ:endQ, "Next");

interp1 = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Hard.Level=", clip(quarterly, -Inf, startQ+40) ...
    , "Indicator.Level=", indicator1 ...
    , "Indicator.Model=", "Ratio" ...
);

interp2 = genip( ...
    yearly, Frequency.QUARTERLY, 2, "sum" ...
    , "Range=", startY:endY ...
    , "Hard.Level=", clip(quarterly, -Inf, startQ+40) ...
    , "Indicator.Level=", indicator2 ...
    , "Indicator.Model=", "Ratio" ...
);

assertEqual(testCase, interp1(:), interp2(:), "AbsTol", 1e-9);

