
%% Test genip

%{
db = databank.fromFred([
    "CLVMNACSCAB1GQDE->ge_gdp"
    "CLVMEURSCAB1GQEU28->eu_gdp"
]);
databank.toCSV(db, "genipTest.csv", Inf);
%}

return

db = databank.fromCSV("genipTest.csv");
db.eu_gdp_yearly = convert(db.eu_gdp, Frequency.YEARLY, 'Method=', @sum);

startInterp = yy(2000);
endInterp = yy(2017);
numInterpYears = round(endInterp - startInterp + 1);
[db.eu_gdp_1, info1] = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', @sum ...
    , 'Range=', startInterp:endInterp ...
    , 'HighRate=', Series(qq(2009,1), 0.972) ...
);

[db.eu_gdp_2, info2] = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', @sum ...
    , 'Range=', startInterp:endInterp ...
    , 'Indicator=', {db.ge_gdp, 1e-3} ...
);

[db.eu_gdp_3, info3] = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', @sum ...
    , 'Range=', startInterp:endInterp ...
    ... , 'HighRate=', Series(qq(2005,1:4), 1) ...
    , 'HighLevel=', db.eu_gdp{qq(2006,1:4)} ...
    ... , 'Indicator=', {db.ge_gdp, 1e-3} ...
);
return

db.eu_gdp_3 = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', @auto ...
    , 'Range=', startInterp:endInterp ...
    , 'Aggregation=', @sum ...
);

stdScale = convert(db.eu_gdp_yearly, Frequency.QUARTERLY, 'Method=', 'QuadSum');
[db.eu_gdp_4, info3] = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', roc(db.ge_gdp) ...
    , 'Range=', startInterp:endInterp ...
    , 'Aggregation=', @sum ...
    , 'StdScale=', stdScale ...
);

db.eu_gdp_roc = roc(db.eu_gdp);

[db.eu_gdp_5, bkf5, info5] = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', roc(db.ge_gdp) ...
    , 'Range=', startInterp:endInterp ...
    , 'Aggregation=', @sum ...
    , 'QuarterlyRate=', db.eu_gdp_roc{qq(2008,1:8)} ...
);

x1 = convert(db.eu_gdp_yearly, Frequency.QUARTERLY, Inf, 'Method=', 'quadsum');
x2 = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', @auto ...
    , 'Aggregation=', @sum ...
);
x3 = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', 1 ...
    , 'Aggregation=', @sum ...
);

x4 = genip( ...
    db.eu_gdp_yearly, Frequency.QUARTERLY, 'Rate', 1 ...
    , 'Aggregation=', @sum ...
    , 'QuarterlyLevel=', db.eu_gdp{qq(2008,1:8)} ...
);

